# Generated by Django 4.1.4 on 2022-12-10 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("webui", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="server",
            name="name",
            field=models.CharField(default="aaa", max_length=256),
            preserve_default=False,
        ),
    ]
