# Generated by Django 4.1.4 on 2022-12-11 01:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("webui", "0002_server_name"),
    ]

    operations = [
        migrations.CreateModel(
            name="NbChanges",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("datetime", models.DateTimeField()),
                ("nb_change", models.IntegerField()),
                (
                    "server",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="webui.server"
                    ),
                ),
            ],
            options={
                "unique_together": {("server", "datetime")},
            },
        ),
    ]
