# Generated by Django 4.1.4 on 2022-12-11 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("webui", "0003_nbchanges"),
    ]

    operations = [
        migrations.AddField(
            model_name="nbchanges",
            name="nb_fail",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="nbchanges",
            name="nb_change",
            field=models.IntegerField(default=0),
        ),
    ]
