- hosts: all
  connection: local
  tasks:
    - name: Record mach_type and phase for later analysis
      ansible.builtin.set_stats:
        data:
          mach_type: "{{ mach_type }}"
          phase: "{{ phase }}"
        per_host: yes
    - name: Task that never changes
      debug:
        msg: Something that never changes!
    - name: Task that always changes
      debug:
        msg: Something that always changes!
      changed_when: true
    - name: Task that sometimes changes
      debug:
        msg: Task that changes when the server is a certain machtype!
      changed_when: mach_type == "FLO"

    - name: Task that can fail
      assert:
        that: mach_type != "TIM"

    - name: A new task that always changes!
      debug:
        msg: A new task that always changes!
      changed_when: true
